# Names carry a generation (var.secret_generation): a deleted secret keeps its
# name for its 7-day recovery window, so recreating the stack inside it either
# restores and imports the old secrets or moves to the next generation
# (README.md, "Tear down"). Never a forced deletion without recovery.
#
# Containers only. The values are written by seed-secrets.sh (generated by
# Secrets Manager itself, never printed) or by the owner, so no password is
# ever in Terraform state, a variable file, Git or a log.

locals {
  db_roles = ["owner", "auth", "exec", "scoped"]
}

resource "aws_secretsmanager_secret" "db_role" {
  for_each                = toset(local.db_roles)
  name                    = "${var.name}/${var.secret_generation}/db/${each.key}"
  description             = "Password of the pac_${each.key} database role (bootstrap sets it on the role)"
  recovery_window_in_days = 7
}

resource "aws_secretsmanager_secret" "test_users" {
  name                    = "${var.name}/${var.secret_generation}/test-users"
  description             = "JSON object user_id -> password for disposable staging identities"
  recovery_window_in_days = 7
}

resource "aws_secretsmanager_secret" "oidc_client" {
  name                    = "${var.name}/${var.secret_generation}/oidc-client-secret"
  description             = "The identity provider's client secret, once a registration exists"
  recovery_window_in_days = 7
}
