"""facility_count_all by geography, against SQL written by hand.

This combination failed with DuplicateAlias before it ever produced a number,
so the fix is only half-proven by "it executes now". These compare the
figures with an independent query written here, not generated by the
compiler under test -- a compiler that joined geography wrongly would agree
with itself.

The reference follows the documented geography contract: a facility is
``org_type = 'Facility'`` (docs/org_hierarchy.md), and geography resolves
through ``zip_territory`` on the organization's ZIP.
"""

from __future__ import annotations

import pytest

from app.analytics.compiler import Compiler
from app.analytics.plan import AnalyticalPlan
from tests.conftest import needs_db

pytestmark = needs_db

R3M = {"kind": "named", "named": "r3m"}


def compiled_rows(anchor, **kw):
    from app.db import owner_transaction
    plan = AnalyticalPlan.model_validate(
        {"metric": "facility_count_all", "time": R3M, **kw})
    q = Compiler(max_rows=5000).compile(plan, anchor=anchor)
    with owner_transaction() as cur:
        cur.execute(q.sql, q.params)
        return cur.fetchall()


def reference(sql, params=()):
    from app.db import owner_transaction
    with owner_transaction() as cur:
        cur.execute(sql, params)
        return cur.fetchall()


def test_by_territory_matches_the_hand_written_count(anchor):
    got = {r["dim0_id"]: int(r["value"]) for r in
           compiled_rows(anchor, dimensions=["territory"])}
    want = {r["t"]: int(r["n"]) for r in reference("""
        SELECT z.territory_name AS t, count(DISTINCT o.org_id) AS n
        FROM organizations o LEFT JOIN zip_territory z ON z.zip = o.zip
        WHERE o.org_type = 'Facility'
        GROUP BY 1""")}
    assert got == want


def test_by_region_matches_the_hand_written_count(anchor):
    got = {r["dim0_id"]: int(r["value"]) for r in
           compiled_rows(anchor, dimensions=["region"])}
    want = {r["g"]: int(r["n"]) for r in reference("""
        SELECT z.region_name AS g, count(DISTINCT o.org_id) AS n
        FROM organizations o LEFT JOIN zip_territory z ON z.zip = o.zip
        WHERE o.org_type = 'Facility'
        GROUP BY 1""")}
    assert got == want


def test_territories_partition_the_total(anchor):
    """Metamorphic: every facility sits in exactly one territory, so the
    breakdown must sum to the undivided count. A join that duplicated rows
    would break this even if each group looked plausible."""
    total = int(compiled_rows(anchor)[0]["value"])
    by_territory = sum(int(r["value"]) for r in
                       compiled_rows(anchor, dimensions=["territory"]))
    assert by_territory == total
    assert total == reference(
        "SELECT count(*) AS n FROM organizations WHERE org_type = 'Facility'")[0]["n"]


def test_a_region_filter_matches_the_hand_written_count(anchor):
    region = reference("SELECT min(region_name) AS r FROM zip_territory")[0]["r"]
    got = int(compiled_rows(anchor, filters={"regions": [region]})[0]["value"])
    want = reference("""
        SELECT count(DISTINCT o.org_id) AS n
        FROM organizations o JOIN zip_territory z ON z.zip = o.zip
        WHERE o.org_type = 'Facility' AND z.region_name = %s""", (region,))[0]["n"]
    assert got == want


def test_a_state_filter_with_a_territory_breakdown(anchor):
    """Geography as both filter and grain -- the shape the review named."""
    got = {r["dim0_id"]: int(r["value"]) for r in
           compiled_rows(anchor, dimensions=["territory"], filters={"states": ["TX"]})}
    want = {r["t"]: int(r["n"]) for r in reference("""
        SELECT z.territory_name AS t, count(DISTINCT o.org_id) AS n
        FROM organizations o LEFT JOIN zip_territory z ON z.zip = o.zip
        WHERE o.org_type = 'Facility' AND o.state = 'TX'
        GROUP BY 1""")}
    assert got == want
    assert got, "Texas has facilities; an empty result would be a vacuous pass"
