"""Application logs: one JSON object per line, sanitised and correlated.

Review of 1 October 2026 ("Other work"). Logs were Python logging's default
text, and span redaction (app/telemetry.py) never covered them. Several
messages interpolate exception text -- a planner failure can quote the
user's question or an entity, a database error the value it refused, a
traceback all of it -- and uvicorn's access log printed the full path with
its query string (an OIDC callback's code and state) beside the client's
address. Logs collected centrally have to be safe to collect.

Every record becomes one line:

    {"ts": "...", "level": "warning", "logger": "app.pipeline",
     "event": "query failed (%s): %s", "args": ["sql", "[redacted]"],
     "error": {"type": "QueryCanceled", "at": "app/pipeline.py:1025"},
     "http_id": "...", "request_id": "...", "run_id": "...", "release": "..."}

* **event** is the message TEMPLATE as written in code, never the
  interpolated text.
* **args** keeps an argument only if it is a number, a boolean, None or
  identifier-shaped text (letters, digits and `_ . : / -`, at most 96
  characters: a route, a model id, a run id). Anything else -- an exception,
  a question, SQL, an address -- is "[redacted]".
* **error** is the exception's type, its stable `code` if it carries one,
  and the innermost frame in this application's code. Never its message or
  traceback: that is where data leaks.
* **http_id** is generated by the server for each HTTP request and returned
  as `X-Request-ID`; **request_id** and **run_id** are the audit row and run
  of the turn being served, once one has started. A client cannot choose
  any of them.
* **uvicorn access lines** become `{"event": "http.access", "method",
  "path", "status"}`: no query string, no client address.

The image starts uvicorn with app/log_config.json, which installs this
formatter before uvicorn writes its first line; the API's lifespan and the
jobs commands call configure(), which does the same where nothing has.
PAC_LOG_FORMAT=text keeps Python's default formatting, for local work only.
"""

from __future__ import annotations

import contextvars
import json
import logging
import os
import re
import sys
from datetime import datetime, timezone
from typing import Any

REDACTED = "[redacted]"

_IDENTIFIER = re.compile(r"^[A-Za-z0-9_.:/-]{1,96}$")
_PATH = re.compile(r"^/[A-Za-z0-9_.:/~%-]{0,199}$")
_CODE = re.compile(r"^[a-z0-9_.-]{1,48}$")

_context: contextvars.ContextVar[dict[str, str]] = contextvars.ContextVar(
    "pac_log_context", default={})

#: The loggers uvicorn configures with its own text handlers.
_UVICORN = ("uvicorn", "uvicorn.error", "uvicorn.access")


def bind(**ids: str | None) -> contextvars.Token:
    """Attach correlation ids to every record logged in this context."""
    return _context.set({**_context.get(), **{k: v for k, v in ids.items() if v}})


def unbind(token: contextvars.Token) -> None:
    _context.reset(token)


def current() -> dict[str, str]:
    return dict(_context.get())


def _arg(value: Any) -> Any:
    if value is None or isinstance(value, (bool, int, float)):
        return value
    if isinstance(value, str) and _IDENTIFIER.match(value):
        return value
    return REDACTED


def _error(exc_info) -> dict[str, Any]:
    kind, value, tb = exc_info
    error: dict[str, Any] = {"type": getattr(kind, "__name__", "Exception")}
    code = getattr(value, "code", None)
    if isinstance(code, str) and _CODE.match(code):
        error["code"] = code
    at = None
    while tb is not None:
        filename = tb.tb_frame.f_code.co_filename.replace("\\", "/")
        if "/app/" in filename:
            at = f"app/{filename.rsplit('/app/', 1)[1]}:{tb.tb_lineno}"
        tb = tb.tb_next
    if at:
        error["at"] = at
    return error


class JsonFormatter(logging.Formatter):
    def __init__(self, release: str | None = None):
        super().__init__()
        self.release = release or os.environ.get("PAC_RELEASE", "dev")

    def format(self, record: logging.LogRecord) -> str:
        out: dict[str, Any] = {
            "ts": datetime.fromtimestamp(record.created, timezone.utc).isoformat(
                timespec="milliseconds"),
            "level": record.levelname.lower(),
            "logger": record.name,
        }
        args = record.args
        if record.name == "uvicorn.access" and isinstance(args, tuple) and len(args) == 5:
            _client, method, path, _version, status = args
            path = str(path).split("?", 1)[0]
            out.update(event="http.access", method=_arg(method),
                       path=path if _PATH.match(path) else REDACTED,
                       status=status if isinstance(status, int) else None)
        else:
            out["event"] = record.msg[:300] if isinstance(record.msg, str) else REDACTED
            if isinstance(args, dict):
                out["args"] = {str(k)[:48]: _arg(v) for k, v in list(args.items())[:20]}
            elif args:
                out["args"] = [_arg(a) for a in (args if isinstance(args, tuple)
                                                 else (args,))[:20]]
        if record.exc_info and record.exc_info[0] is not None:
            out["error"] = _error(record.exc_info)
        out.update(_context.get())
        out["release"] = self.release
        return json.dumps(out, ensure_ascii=True, default=lambda _: REDACTED)


class _Handler(logging.StreamHandler):
    """Marks the handler this module installed, so configuring twice
    replaces it rather than doubling every line."""


def configure(settings=None) -> None:
    """Send every record -- the application's, uvicorn's and the libraries'
    -- through JsonFormatter on stderr. Idempotent. Leaves any other
    handler on the root logger alone (a test runner's, for instance)."""
    if settings is None:
        from app.config import get_settings
        settings = get_settings()
    if settings.log_format == "text":
        return
    root = logging.getLogger()
    for handler in list(root.handlers):
        if isinstance(handler, _Handler):
            root.removeHandler(handler)
    # uvicorn started with app/log_config.json has installed it already.
    if not any(isinstance(h.formatter, JsonFormatter) for h in root.handlers):
        handler = _Handler(sys.stderr)
        handler.setFormatter(JsonFormatter(settings.release))
        root.addHandler(handler)
    root.setLevel(settings.log_level.upper())
    # uvicorn's own handlers print plain text, the access log with query
    # strings and addresses. Theirs go; records reach the root's instead.
    for name in _UVICORN:
        logger = logging.getLogger(name)
        for existing in list(logger.handlers):
            logger.removeHandler(existing)
        logger.propagate = True
