#!/usr/bin/env python3
"""Create the database, roles and schema.

Run as a PostgreSQL superuser. Passwords are taken from the environment when
present and generated otherwise; generated values are written to .env, which is
gitignored. No password is ever written into a migration or committed.

  python3 scripts/bootstrap_db.py [--admin-dsn postgresql://...] [--drop]
"""

from __future__ import annotations

import argparse
import os
import pathlib
import secrets
import sys

import psycopg
from psycopg import sql

ROOT = pathlib.Path(__file__).resolve().parent.parent
MIGRATIONS = ROOT / "migrations"
ENV_FILE = ROOT / ".env"

DB_NAME = os.environ.get("PAC_DB_NAME", "pharma_analytics")
OWNER = "pac_owner"

# login role -> privilege role it is granted
LOGIN_ROLES = {
    "pac_auth_login": "pac_auth",
    "pac_exec_login": "pac_rt_exec",
    "pac_scoped_login": "pac_rt_scoped",
}

ENV_KEYS = {
    "pac_owner": "PAC_DB_OWNER_PASSWORD",
    "pac_auth_login": "PAC_DB_AUTH_PASSWORD",
    "pac_exec_login": "PAC_DB_EXEC_PASSWORD",
    "pac_scoped_login": "PAC_DB_SCOPED_PASSWORD",
}


def resolve_passwords() -> dict[str, str]:
    existing = {}
    if ENV_FILE.exists():
        for line in ENV_FILE.read_text().splitlines():
            if "=" in line and not line.strip().startswith("#"):
                k, _, v = line.partition("=")
                existing[k.strip()] = v.strip()
    out = {}
    for role, key in ENV_KEYS.items():
        out[role] = os.environ.get(key) or existing.get(key) or secrets.token_urlsafe(24)
    return out


def write_env(passwords: dict[str, str]) -> None:
    lines = [
        "# Generated by scripts/bootstrap_db.py. Gitignored -- do not commit.",
        f"PAC_DB_NAME={DB_NAME}",
        "PAC_DB_HOST=127.0.0.1",
        "PAC_DB_PORT=5432",
        "PAC_DB_OWNER_USER=pac_owner",
        "PAC_DB_AUTH_USER=pac_auth_login",
        "PAC_DB_EXEC_USER=pac_exec_login",
        "PAC_DB_SCOPED_USER=pac_scoped_login",
    ]
    for role, key in ENV_KEYS.items():
        lines.append(f"{key}={passwords[role]}")
    ENV_FILE.write_text("\n".join(lines) + "\n")
    ENV_FILE.chmod(0o600)
    print(f"  wrote {ENV_FILE} (0600)")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--admin-dsn", default=os.environ.get("PAC_ADMIN_DSN", "postgresql:///postgres"))
    ap.add_argument("--drop", action="store_true", help="drop and recreate the database")
    args = ap.parse_args()

    passwords = resolve_passwords()

    print("== roles and database ==")
    with psycopg.connect(args.admin_dsn, autocommit=True) as conn, conn.cursor() as cur:
        # Owner first: it must exist before the database can be assigned to it.
        cur.execute("SELECT 1 FROM pg_roles WHERE rolname = %s", (OWNER,))
        if cur.fetchone():
            cur.execute(
                sql.SQL("ALTER ROLE {} WITH LOGIN PASSWORD {}").format(
                    sql.Identifier(OWNER), sql.Literal(passwords[OWNER])
                )
            )
        else:
            cur.execute(
                sql.SQL(
                    "CREATE ROLE {} WITH LOGIN PASSWORD {} "
                    "NOSUPERUSER NOCREATEROLE NOCREATEDB NOBYPASSRLS"
                ).format(sql.Identifier(OWNER), sql.Literal(passwords[OWNER]))
            )
        print(f"  {OWNER} ready")

        # Privilege roles (NOLOGIN). Created here, in the administrative phase,
        # because pac_owner deliberately has no CREATEROLE.
        for privilege in ("pac_rt_exec", "pac_rt_scoped", "pac_auth"):
            cur.execute("SELECT 1 FROM pg_roles WHERE rolname = %s", (privilege,))
            if not cur.fetchone():
                cur.execute(
                    sql.SQL(
                        "CREATE ROLE {} NOLOGIN NOSUPERUSER "
                        "NOCREATEDB NOCREATEROLE NOBYPASSRLS"
                    ).format(sql.Identifier(privilege))
                )
            print(f"  privilege role {privilege} ready")

        if args.drop:
            cur.execute(
                sql.SQL("DROP DATABASE IF EXISTS {} WITH (FORCE)").format(sql.Identifier(DB_NAME))
            )
            print(f"  dropped {DB_NAME}")

        cur.execute("SELECT 1 FROM pg_database WHERE datname = %s", (DB_NAME,))
        if not cur.fetchone():
            cur.execute(
                sql.SQL("CREATE DATABASE {} OWNER {}").format(
                    sql.Identifier(DB_NAME), sql.Identifier(OWNER)
                )
            )
            print(f"  created database {DB_NAME}")
        else:
            print(f"  database {DB_NAME} exists")

    # Migrations run as the owner so every object is owned by a non-superuser
    # role that the runtime roles are not members of.
    owner_dsn = f"postgresql://{OWNER}:{passwords[OWNER]}@127.0.0.1:5432/{DB_NAME}"

    print("== migrations ==")
    with psycopg.connect(owner_dsn, autocommit=True) as conn, conn.cursor() as cur:
        for path in sorted(MIGRATIONS.glob("*.sql")):
            cur.execute(path.read_text())
            print(f"  applied {path.name}")

    print("== login roles ==")
    with psycopg.connect(args.admin_dsn, autocommit=True) as conn, conn.cursor() as cur:
        for login, privilege in LOGIN_ROLES.items():
            cur.execute("SELECT 1 FROM pg_roles WHERE rolname = %s", (login,))
            stmt = "ALTER ROLE {} WITH LOGIN PASSWORD {}" if cur.fetchone() else (
                "CREATE ROLE {} WITH LOGIN PASSWORD {} "
                "NOSUPERUSER NOCREATEROLE NOCREATEDB NOBYPASSRLS"
            )
            cur.execute(
                sql.SQL(stmt).format(sql.Identifier(login), sql.Literal(passwords[login]))
            )
            # Exactly one privilege role per login role: a scoped login has no
            # membership path to pac_rt_exec, so SET ROLE cannot escalate it.
            cur.execute(
                sql.SQL("GRANT {} TO {}").format(
                    sql.Identifier(privilege), sql.Identifier(login)
                )
            )
            print(f"  {login} -> {privilege}")

    with psycopg.connect(owner_dsn, autocommit=True) as conn, conn.cursor() as cur:
        cur.execute(
            sql.SQL("GRANT CONNECT ON DATABASE {} TO {}, {}, {}").format(
                sql.Identifier(DB_NAME),
                sql.Identifier("pac_auth_login"),
                sql.Identifier("pac_exec_login"),
                sql.Identifier("pac_scoped_login"),
            )
        )

    write_env(passwords)
    print("\nbootstrap complete")
    return 0


if __name__ == "__main__":
    sys.exit(main())
