#!/usr/bin/env python3
"""Render docs/COVERAGE_BY_INVARIANT.md from evidence/invariants.json.

    python3 scripts/coverage_report.py [--check]

--check exits 1 if the document on disk differs from what the data renders,
so the report cannot drift from the map it is generated from.
"""

from __future__ import annotations

import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
OUT = ROOT / "docs" / "COVERAGE_BY_INVARIANT.md"


def render() -> str:
    data = json.loads((ROOT / "evidence" / "invariants.json").read_text())
    lines = ["# Coverage by business invariant", "",
             "Generated by `scripts/coverage_report.py` from `evidence/invariants.json`; do not edit",
             "by hand. A test count says how many checks ran; this says which business properties are",
             "checked against an independent oracle -- SQL written in the test from the documented",
             "definition, or numbers worked out by hand -- and which are not.", "",
             "| Invariant | Evidence | Tests | Gap |", "|---|---|---:|---|"]
    for inv in data["invariants"]:
        lines.append(f"| **{inv['id']}**: {inv['statement']} | {inv['kind']} | {len(inv['tests'])} | "
                     f"{inv.get('gap', '—')} |")
    lines += ["", "## Tests behind each invariant", ""]
    for inv in data["invariants"]:
        lines.append(f"- **{inv['id']}**: " + ", ".join(f"`{t.split('/')[-1]}`" for t in inv["tests"]))
    lines += ["", "## Evidence that is not a numerical oracle", ""]
    lines += [f"- **{k.replace('_', ' ')}**: {v}" for k, v in data["not_numerical"].items()]
    lines += ["", "Same-schema fixture profiles (`scripts/fixture_profile.py`: unfamiliar names, skew,",
              "source omissions, unknown classifications, an ISO week-53 history, an ingestion series)",
              "run the invariants that cite `test_fixture_profiles.py` on data unlike the supplied set.", ""]
    return "\n".join(lines)


def main() -> int:
    text = render()
    if "--check" in sys.argv:
        return 0 if OUT.exists() and OUT.read_text() == text else 1
    OUT.write_text(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
