#!/usr/bin/env python3
"""Generate docs/DEMO.md by running a real conversation against the real data.

Not a mock-up: every number below comes from the loaded dataset through the
same pipeline the UI uses. The transcript records what the system actually did,
including where it refuses.

  python3 scripts/make_demo.py
"""

from __future__ import annotations

import datetime as dt
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "docs" / "DEMO.md"

# The sequence is chosen to show the boundary, not just the happy path: a
# frozen cohort, a refused pricing request, a refused cross-territory request,
# a Director seeing more than a RAM, an Exec seeing pricing neither can, and an
# impossible market share reported honestly.
SCRIPT = [
    ("ram", "What are my top 5 accounts by pack units this quarter?", True,
     "A RAM signs in. Scope is applied before anything is aggregated."),
    ("ram", "Now break that down by quarter", True,
     "Follow-up. The account population is kept; a grain is added."),
    ("ram", "Exclude 340B accounts", True,
     "Another follow-up. Only the 340B filter changes -- the ranking and window survive."),
    ("ram", "What is my total revenue in dollars this quarter?", False,
     "Pricing is not available at this access level. The answer says so and "
     "reports volume in packs instead -- a labelled substitution, not a refusal."),
    ("ram", "Show me sales in the Texas territory", False,
     "A territory outside scope is refused by name, not silently re-scoped."),
    ("director", "How are the territories in my region performing this quarter?", True,
     "A Director sees every territory in their region -- and only those."),
    ("exec", "What is our total revenue this quarter?", True,
     "An Exec with can_view_wac = 1 is the only principal who sees pricing."),
    ("exec", "What is our market share for Zenovax?", True,
     "The supplied market data holds no company rows, so this ratio is impossible. "
     "It is reported with both components and labelled, not clamped."),
]


def main() -> int:
    from app.auth.policy import principal_for_user_id
    from app.config import get_settings
    from app.db import close_pools, owner_transaction
    from app.llm.planner import build_planner
    from app.pipeline import Pipeline

    settings = get_settings()
    planner = build_planner(settings)
    pipeline = Pipeline(planner)
    dataset = pipeline.current_dataset()

    with owner_transaction() as cur:
        cur.execute(
            """
            SELECT DISTINCT ON (u.role) u.user_id, u.email, u.full_name, u.role,
                   u.territory_name, u.region_name
            FROM users u
            ORDER BY u.role,
                     CASE WHEN u.role = 'exec' THEN 1
                          WHEN u.role = 'director' AND EXISTS (
                               SELECT 1 FROM zip_territory z
                               WHERE z.region_name = u.region_name) THEN 1
                          WHEN u.role = 'ram' AND EXISTS (
                               SELECT 1 FROM zip_territory z
                               WHERE z.territory_name = u.territory_name) THEN 1
                          ELSE 2 END, u.user_id
            """
        )
        rows = {r["role"]: r for r in cur.fetchall()}

    # Built directly from the users table -- no password is minted, so running
    # this never disturbs credentials that have been issued to anyone.
    principals = {role: principal_for_user_id(row["user_id"]) for role, row in rows.items()}

    provider = settings.llm_provider
    model = getattr(planner, "model_id", "deterministic offline planner")

    out: list[str] = []
    w = out.append

    w("# Demo transcript")
    w("")
    w("Generated by `scripts/make_demo.py` against the loaded dataset. Every")
    w("number is a real query result from the same pipeline the chat UI uses;")
    w("nothing here is illustrative.")
    w("")
    w(f"- Generated: `{dt.datetime.now(dt.timezone.utc).isoformat(timespec='seconds')}`")
    w(f"- Dataset: `{dataset['dataset_id']}` ({dataset['load_mode']}), "
      f"{dataset['row_counts'].get('sales', 0):,} sales rows")
    w(f"- Planner: `{provider}` — {model}")
    if provider == "offline":
        w("")
        w("> **The planner here is the deterministic keyword planner, not a language")
        w("> model.** It is what runs when no model is configured. The transcript")
        w("> therefore demonstrates scoping, metric correctness, refusals and")
        w("> data-quality reporting — it is not a demonstration of natural-language")
        w("> understanding, and the answers should not be read as one.")
    w("")
    w("---")
    w("")

    conversations: dict[str, str] = {}
    current_role: str | None = None

    for role, question, expect_answer, commentary in SCRIPT:
        principal = principals.get(role)
        if principal is None:
            w(f"_(no usable {role} account in this dataset; step skipped)_")
            continue

        if role != current_role:
            current_role = role
            w(f"## Signed in as {principal.full_name} — {principal.role.upper()}")
            w("")
            w(f"Scope: **{principal.scope_description}** · "
              f"Pricing: **{'visible' if principal.wac_authorized else 'restricted'}**")
            w("")

        result = pipeline.ask(
            principal, question,
            conversation_id=conversations.get(role), include_sql=True,
        )
        conversations[role] = result.conversation_id

        w(f"> {commentary}")
        w("")
        w(f"**Q:** {question}")
        w("")
        w(f"**A:** {result.message}")
        w("")

        if result.alternative:
            w(f"*{result.alternative}*")
            w("")

        answer = result.answer
        if answer and answer.table:
            headers = [c for c in answer.columns]
            if len(answer.table[0]) and "dim0" in answer.table[0]:
                w("| " + " | ".join(headers) + " |")
                w("|" + "|".join(["---"] * len(headers)) + "|")
                for row in answer.table[:6]:
                    cells = []
                    for i in range(len(headers) - 1):
                        cells.append(str(row.get(f"dim{i}", "")))
                    cells.append(row["value_formatted"])
                    w("| " + " | ".join(cells) + " |")
                if len(answer.table) > 6:
                    w(f"| … | _{len(answer.table) - 6} more rows_ |")
                w("")

        if answer:
            w(f"<sub>{answer.scope_note} {answer.period_note}</sub>")
            w("")
            for note in answer.notes:
                w(f"<sub>ℹ️ {note}</sub>")
                w("")
            for warning in answer.warnings:
                w(f"> ⚠️ {warning}")
                w("")

        if result.status == "denied":
            w(f"<sub>Status: **refused** · request `{result.request_id}`</sub>")
            w("")

        # Pricing must be absent from a non-Exec's SQL, so show it.
        if result.sql and not principal.wac_authorized:
            has_wac = "wac" in result.sql.lower()
            w(f"<sub>SQL contains `wac`: **{'YES — LEAK' if has_wac else 'no'}**</sub>")
            w("")

        w(f"<sub>{result.timings.get('db_ms', 0)} ms in the database, "
          f"{result.timings.get('total_ms', 0)} ms end to end</sub>")
        w("")
        w("---")
        w("")

    w("## What this shows")
    w("")
    w("| Behaviour | Where |")
    w("|---|---|")
    w("| Territory scope applied before aggregation | RAM's first answer |")
    w("| Follow-up keeps the population, adds a grain | \"break that down by quarter\" |")
    w("| Follow-up changes one filter, keeps the ranking | \"exclude 340B\" |")
    w("| Pricing withheld, volume substituted and labelled | RAM's revenue question |")
    w("| Out-of-scope territory refused by name | \"sales in the Texas territory\" |")
    w("| Director sees strictly more than the RAM inside it | Director's territories |")
    w("| Only an authorised Exec sees WAC | Exec's revenue answer |")
    w("| Impossible data reported, not repaired | Zenovax market share |")
    w("")

    OUT.write_text("\n".join(out))
    print(f"wrote {OUT.relative_to(ROOT)} ({len(out)} lines)")
    close_pools()
    return 0


if __name__ == "__main__":
    sys.exit(main())
