#!/usr/bin/env python3
"""The staging module's resource inventory, from its plans with a mocked provider.

    TERRAFORM=<path> python3 scripts/staging_plan_inventory.py > infra/aws-staging/PLAN_INVENTORY.md

Runs `terraform test -verbose` in infra/aws-staging (tests/plan.tftest.hcl:
a mocked AWS provider, no credentials, no API call, nothing created), reads
every address each plan would create, and writes them per configuration,
with what each step of README.md's "Create" adds. Exact for the addresses
and their count; every attribute AWS computes is unknown in a mocked plan.
"""

from __future__ import annotations

import collections
import os
import pathlib
import re
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
MODULE = ROOT / "infra" / "aws-staging"
SHAPES = {
    "foundation_without_an_image": "Foundation (README step 3): no image_digest",
    "deployable_at_zero_tasks": "Deployable (step 6): image_digest set, app_desired_count = 0",
    "private_tasks_behind_nat": "Private tasks: egress_mode = \"nat\"",
    "failover_shape": "Failover test: app_desired_count = 2, db_multi_az = true",
}


def plans() -> dict[str, list[str]]:
    env = {**os.environ, "AWS_EC2_METADATA_DISABLED": "true", "AWS_ACCESS_KEY_ID": "",
           "AWS_SECRET_ACCESS_KEY": "", "AWS_SESSION_TOKEN": ""}
    env.pop("AWS_PROFILE", None)
    out = subprocess.run([os.environ.get("TERRAFORM", "terraform"), "test", "-verbose", "-no-color"],
                         cwd=MODULE, env=env, capture_output=True, text=True)
    if out.returncode != 0:
        sys.exit(out.stdout[-2000:] + out.stderr[-2000:])
    runs: dict[str, list[str]] = {}
    current = None
    for line in out.stdout.splitlines():
        m = re.match(r'\s*run "([^"]+)"\.\.\. (pass|fail)', line)
        if m:
            current = m.group(1)
            runs[current] = []
            continue
        m = re.match(r"\s*# (\S+) will be created", line)
        if m and current:
            runs[current].append(m.group(1))
    return runs


def by_type(addresses: list[str]) -> str:
    kinds = collections.Counter(re.sub(r"\[.*?\]$", "", a).rsplit(".", 1)[0] for a in addresses)
    return "\n".join(f"| `{k}` | {n} |" for k, n in sorted(kinds.items()))


def main() -> int:
    runs = plans()
    base = set(runs["foundation_without_an_image"])
    out = ["# Staging plan inventory", "",
           "Generated by `scripts/staging_plan_inventory.py` from `terraform test -verbose` "
           "(`tests/plan.tftest.hcl`: a mocked AWS provider, no credentials, no API call, "
           "nothing created). Every address and count is what Terraform would plan; values AWS "
           "computes are unknown here, and nothing here shows that AWS accepts the plan.", "",
           "| Configuration | Resources to create |", "|---|---:|"]
    out += [f"| {title} | {len(runs[key])} |" for key, title in SHAPES.items()]
    for key in ("deployable_at_zero_tasks", "private_tasks_behind_nat", "failover_shape"):
        added = sorted(set(runs[key]) - base)
        out += ["", f"## {SHAPES[key]}: beyond the foundation", ""]
        out += [f"- `{a}`" for a in added] or ["- nothing"]
    out += ["", "## The foundation, by resource type", "", "| Type | Count |", "|---|---:|",
            by_type(runs["foundation_without_an_image"]), "",
            "## Every address in the foundation", ""]
    out += [f"- `{a}`" for a in sorted(runs["foundation_without_an_image"])]
    sys.stdout.write("\n".join(out) + "\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
